mutation postComment($object: comments_insert_input!){
  insert_comments_one(object: $object)
  {
    id
  }
},

query getComment($contributionId: uuid){
  comments(where: {contribution:{id: {_eq: $contributionId}}}, order_by:{createAt: asc}){
    id,
    content,
    createAt,
    user{
      fullName
    }
  }
}