query getContribute($idMgz: uuid){
  contributions(where: {magazine: {id: {_eq: $idMgz}}}){
    title
    magazine{
      label
    }
    id
    user{
      fullName
      faculty{
        label
      }
    }
    userByPublicBy{
      fullName
    }
    isSelected
    faculty{
      label
    }
    artical
    image
    deleted
    createdAt
    updatedAt
  }
}