
query getContribute($idMgz: uuid){
  contributions(where: {magazine: {id: {_eq: $idMgz}}}){
    title
    magazine{
      label
    }
    id
    user{
      fullName
      faculty{
        label
      }
    }
    userByPublicBy{
      fullName
    }
    isSelected
    faculty{
      label
    }
    artical
    image
    deleted
    createdAt
    updatedAt
  }
},

query getContributeByUserId($idUser: uuid){
  contributions(where: {user: {id: {_eq: $idUser}}}){
    title
    magazine{
      label
    }
    id
    user{
      faculty{
        label
      }
    }
    userByPublicBy{
      fullName
    }
    isSelected
    faculty{
      label
    }
    artical
    image
    deleted
    createdAt
    updatedAt
  }
}

mutation addContribution($object: contributions_insert_input!) {
  insert_contributions(objects: [$object]) {
    affected_rows
    returning {
      id
    }
  }
}