query getMagazine($where: magazines_bool_exp){
  magazines(where: $where) {
    id
    label
    closureTemp
    closureFinal
    createdAt
  }
}

mutation addMagazine($object: magazines_insert_input!) {
  insert_magazines(objects: [$object]) {
    affected_rows
    returning {
      id
    }
  }
}