query getUsers {
    users (limit: 10) {
        id
    }
}

mutation addUser($object: users_insert_input!) {
  insert_users(objects: [$object]) {
    affected_rows
    returning {
      id
    }
  }
}